# Generated by Django 5.1.1 on 2024-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnualProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_well_number", models.IntegerField()),
                ("total_oil", models.IntegerField()),
                ("total_gas", models.IntegerField()),
                ("total_brine", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="QuarterlyProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_well_number", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("oil", models.IntegerField()),
                ("gas", models.IntegerField()),
                ("brine", models.IntegerField()),
            ],
        ),
    ]
