# Generated by Django 5.1.1 on 2024-09-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annual", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualproduction",
            name="api_well_number",
            field=models.IntegerField(unique=True),
        ),
    ]
